### ISSUE TITLE
Feature request: An option to skip re-encoding the audio

### ISSUE THREAD

**Issue by Uranite** [SuspiciousDuck/grav1an#1]
It'll be great if there is an option to skip re-encoding the audio, as the audio might be already lossy, but because it doesn't have the bitrate tag it might get re-encoded

**Comment by SuspiciousDuck** [comment]
[Latest commit](https://github.com/SuspiciousDuck/grav1an/commit/413a5234eba08d01bc18c56700a04884dffe5dda) should implement this (probably)
